# Generated by Django 3.2.5 on 2021-08-29 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=15)),
                ('family_members', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(default='394180', max_length=6)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('customer_email', models.EmailField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=15)),
                ('loan_type', models.CharField(choices=[('Home loan', 'Home loan'), ('Machine loan', 'Machine loan'), ('Student loan', 'Student loan'), ('Other loan', 'Other loan')], max_length=20)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('customer_email', models.EmailField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=15)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('customer_email', models.EmailField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=15)),
                ('vehicle_brand', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('registration_year', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(default='394180', max_length=6)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('customer_email', models.EmailField(max_length=65)),
            ],
        ),
    ]
