# Generated by Django 3.2.5 on 2021-08-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurance',
            name='family_members',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('cng', 'cng'), ('electric', 'electric')], max_length=15),
        ),
    ]
