# Generated by Django 3.2.5 on 2021-08-29 12:55

import django.core.validators
from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210829_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinsurance',
            name='registration_year',
        ),
        migrations.AddField(
            model_name='vehicleinsurance',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1984), services.models.max_value_current_year], verbose_name='year'),
            preserve_default=False,
        ),
    ]
