# Generated by Django 3.2.5 on 2021-08-29 14:19

import django.core.validators
from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210829_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinsurance',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicleinsurance',
            name='registration_year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1996), services.models.max_value_current_year]),
        ),
    ]
